language: d
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - libevent-dev

d:
  - dmd-nightly
  - dmd-beta
  - dmd
  - dmd-2.078.3
  - dmd-2.077.1
  #- dmd-2.076.1 dub version in here is too error prone for timeouts
  - ldc-beta
  - ldc
  - ldc-1.7.0
  - ldc-1.6.0

script:
  - dub test --compiler=$DC || exit 1
